### ISSUE TITLE
Enable JSON Arguments To CoreIR Generators

### ISSUE THREAD

**Issue by David-Durst** [leonardt/pycoreir#108]
Pycoreir doesn't support CoreIR's JSON type. This is necessary to create ROMs.

The necessary changes include:
1. https://github.com/leonardt/pycoreir/blob/master/coreir/type.py#L21 - adding a JSON type
1. https://github.com/leonardt/pycoreir/blob/master/coreir/context.py#L110 - adding a JSON value
1. https://github.com/rdaly525/coreir/blob/master/src/coreir-c/values-c.cpp - adding a libcoreir_c.COREValueJSON
1. https://github.com/rdaly525/coreir/blob/master/src/coreir-c/types-c.cpp - adding a libecoreir_c.CoreJSON

**Comment by leonardt** [comment]
Json support was added awhile ago (and the newly tested magma rom primitive uses this)
