### ISSUE TITLE
Loading module without definition and using autocomplete in terminal crashes

### ISSUE THREAD

**Issue by David-Durst** [leonardt/pycoreir#33]
Loading a CoreIR c++ module and trying to do autocomplete on it in the terminal when it doesn't have a definition causes the below crash. (Note that this code depends on the import_generator function in this pull request https://github.com/leonardt/pycoreir/pull/32) 
```
>>> from coreir.context import *
>>> from magma.backend.coreir_ import CoreIRBackend
>>> from magma import *
>>> c = Context()
>>> cirb = CoreIRBackend(c)
>>> dehydrate = cirb.context.import_generator("aetherlinglib", "dehydrate")(hydratedType = cirb.get_type(Array(3, Array(5, BitIn)), True))
>>> dehydrate.Assertion failed: (m->hasDef() && "Does not have def!"), function DirectedModule, file directedview.cpp, line 42.
Abort trap: 6
````

**Comment by leonardt** [comment]
Fixed in https://github.com/leonardt/pycoreir/commit/e369b4fe01586bd0e7546ee0f8044788b93432f5
