### ISSUE TITLE
Python objects are different for the same coreir object

### ISSUE THREAD

**Issue by rdaly525** [leonardt/pycoreir#66]
```
import coreir
c = coreir.Context()
assert c.get_namespace("coreir") == c.get_namespace("coreir")
```
fails the assert.

Similar with Namespace.generators, and Namespace.modules.

Is this intended behavior?

**Comment by rdaly525** [comment]
I would like to have a namespace (or module, or generator) as a key in a python dict. Is there an intended method to do this? the 'ptr' field unfortunately is unhashable.

**Comment by leonardt** [comment]
Try this out https://github.com/leonardt/pycoreir/pull/67

I had to use some ctypes logic to convert the pointers to their underlying int representation, then I use that for `__eq__` and `__hash__`
