### ISSUE TITLE
Create manylinux binary wheels

### ISSUE THREAD

**Issue by Kuree** [leonardt/pycoreir#76]
Maybe I'm the only person who doesn't want `sudo` install or mess around `LD_LIBRARY_PATH`, but I'd really appreciate if you can provide manylinux wheels that package the shared libraries.

I've created a manylinux docker image that works on modern gcc (8.3) and CMake (3.14) and the latest igraph. It works on both of my C++ python libraries. You can find the docker image [here](https://github.com/Kuree/cgra_pnr_build/blob/master/docker/Dockerfile) and [how](https://github.com/Kuree/cgra_pnr_build/blob/master/.travis.yml) I upload them to PyPi.

Since CoreIR is using an ancient gcc/g++, I think the default manylinux image may work straight out of the box. You just need to build the library there and then package the `*.so` files in `setup.py`.

Please let me know if you have any questions. Feel free to close this issue if you think it's too difficult or not necessary to do.

**Comment by leonardt** [comment]
This makes sense, I'll take a look at doing it when I get some time (or someone else is welcome to set it up).

**Comment by Kuree** [comment]
Tried to modified the `setup.py` to allow python extension. Here is what I did:

```diff
diff --git a/coreir/lib.py b/coreir/lib.py
index 8415a77..a94c9ad 100644
--- a/coreir/lib.py
+++ b/coreir/lib.py
@@ -11,7 +11,7 @@ def load_shared_lib(lib):
         shared_lib_ext = "dylib"
     else:
         raise NotImplementedError(_system)
-
+    lib = os.path.join(os.path.dirname(os.path.abspath(__file__)), lib)
     return cdll.LoadLibrary("{}.{}".format(lib, shared_lib_ext))
 
 
diff --git a/setup.py b/setup.py
index bd5f9f5..6efe15b 100644
--- a/setup.py
+++ b/setup.py
@@ -1,4 +1,39 @@
-from setuptools import setup
+import subprocess
+import os
+from setuptools import setup, Extension
+from setuptools.command.build_ext import build_ext
+import glob
+import shutil
+
+
+COREIR_PATH = "coreir-cpp"
+COREIR_REPO = "https://github.com/rdaly525/coreir"
+COREIR_NAME = "coreir"
+
+class CoreIRExtension(Extension):
+    def __init__(self, name, sourcedir=''):
+        Extension.__init__(self, name, sources=[])
+        self.sourcedir = os.path.abspath(sourcedir)
+
+
+class CoreIRBuild(build_ext):
+    def run(self):
+        if not os.path.isdir(COREIR_PATH):
+            subprocess.check_call(["git", "clone", COREIR_REPO,
+                                   COREIR_PATH])
+        subprocess.check_call(["make", "-C", COREIR_PATH, "-j2"])
+        # we only have one extension
+        assert len(self.extensions) == 1
+        ext = self.extensions[0]
+        extdir = os.path.abspath(os.path.dirname(self.get_ext_fullpath(ext.name)))
+        extdir = os.path.join(extdir, COREIR_NAME)
+        if not os.path.isdir(extdir):
+            os.mkdir(extdir)
+        # copy everything over
+        for filename in glob.glob(os.path.join(COREIR_PATH, "lib", "*.so")):
+            shutil.copy(filename, extdir)
+
 
 with open("README.md", "r") as fh:
     long_description = fh.read()
@@ -14,5 +49,8 @@ setup(
     author_email='lenny@cs.stanford.edu',
     long_description=long_description,
     long_description_content_type="text/markdown",
-    install_requires=["hwtypes>=1.0.*"]
+    install_requires=["hwtypes>=1.0.*"],
+    ext_modules=[CoreIRExtension('coreir')],
+    cmdclass=dict(build_ext=CoreIRBuild),
+    zip_safe=False,
 )
```

It builds fine, but there is a problem regarding the `libcoreir-c.so`. Since it's dynamically linked against `libcoreir.so`, even though the system loads `libcoreir-c.so` through absolute path, python still tries to load `libcoreir.so`, which is not in the system path. One way to do that is to have a flag in coreir's `Makefile` that link `libcore-c.so` statically when compiling for C extensions. The problem might be easier to solve if coreir switches to modern build systems, such as `CMake`.

@leonardt This may require some changes in how coreir is built, so I will leave this to you. Once you have resolved this issue I can send a PR that builds the wheel in `manylinux` docker environment.

**Comment by leonardt** [comment]
Cmake build system was merged into dev (see https://github.com/rdaly525/coreir/pull/717), so we should wait until that's been released (hopefully it makes it easier to do this static linking). I think linking it statically makes sense if we're distributing the binary with the Python package (otherwise we would need to require the user install other external (to pip) dependencies which negates some of the benefits of packaging the extension with the python package. In fact, it might make things more complicated if there are conflicts in the user envrionment)

**Comment by Kuree** [comment]
See #82
