### ISSUE TITLE
Adding python objects as metadata to coreir objects.

### ISSUE THREAD

**Issue by rdaly525** [leonardt/pycoreir#79]
It would be nice to be able to attach arbitrary python metadata to coreir objects (like instances and modules). This might be difficult since the python object representing a coreir object does not persist across the api calls. @leonardt thoughts on any easy ways to accomplish this?

**Comment by leonardt** [comment]
Can you provide a more concrete example of what kind of metadata you would like to attach and how you would like to use it? I'm having trouble understanding exactly what functionality you need.

**Comment by rdaly525** [comment]
For example I would like to attach a python class object to an instance. A use case of this is in the automatic mapper where I need to associate an instance of a peak module with the peak instruction (which is a python object).

There are obviously other ways of accomplishing this, namely by the user keeping around a custom datastructure associating the instance with the peak instruction.

**Comment by leonardt** [comment]
We could add a `metadata` attribute to coreir objects which is a dictionary mapping string keys to anything the user wants. That's a fairly simple extension. The bigger issue, which I believe you're referring to in your original post, is that new objects get constructed whenever an API method is invoked, even though it may be referring to an object that was already retrieved via the API earlier. I think the way to resolve this would be to implement some sort of cacheing mechanism (either using decorators or metaclasses) which enforces an invariant that any coreir object (pointer) only has a single corresponding Python object. This could be done simply by hashing the raw pointer value (accessible via the ctypes api).

**Comment by leonardt** [comment]
Every coreir object is (or should be) a subclass of `CoreIRType` https://github.com/leonardt/pycoreir/blob/master/coreir/base.py#L13-L17

We could do some metaclass logic similar to the cacheing of BitVector types which hashes on the `ptr` and `context` values.

**Comment by rdaly525** [comment]
That seems reasonable to me. I could take a stab at it if you point me to the metaclass logic for BitVectors.

**Comment by leonardt** [comment]
https://github.com/leonardt/hwtypes/blob/master/hwtypes/bit_vector_abc.py#L14-L90
This task is slightly different because this doesn't use the `__getitem__` syntax, and instead is hooking into the instance parameters.  You'll probably find this useful at some point: https://blog.ionelmc.ro/2015/02/09/understanding-python-metaclasses/ (particularly the diagrams which detail the order in which the various dunderscore methods are called)
