### ISSUE TITLE
Support for using local coreir binary/library

### ISSUE THREAD

**Issue by rdaly525** [leonardt/pycoreir#90]
I would like to easily develop coreir/pycoreir on local branches. Is there any way I can revert back to the old pip install behavior when making changes on local branches?

If I pip install -e, it will try to build the static version of CoreIR which I do not want. I want to be able to specify a local path for the dynamical libraries.

**Comment by leonardt** [comment]
@Kuree do you know of a way having the python package optionally build the extension? E.g. is there a command we can pass to setup.py to indicate to skip an extension?

**Comment by leonardt** [comment]
@rdaly525 for now, I think one workaround you could try is removing the build extension on this line from your setup.py here https://github.com/leonardt/pycoreir/blob/master/setup.py#L89

**Comment by Kuree** [comment]
Here are some solutions I can think of
1. You can symbolic link `coreir-cpp` to your local repo then call `pip install -e .`
2. You can just delete the libraries that shipped with the wheel. The code should just run fine.

`pip` does allow custom options to be send to the build system, see: https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides
This requires some tweaking on how the `-static` flags and other stuff are used.

**Comment by rdaly525** [comment]
@leonardt, Thanks, commenting out 'ext_modules' and 'cmd_class' works great.
